import { IMovie } from "./movie.interface";

export const MOVIES: IMovie[] = [
  {
    id: 1,
    original_title: "The Movie 1",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
  {
    id: 2,
    original_title: "The Movie 2",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
  {
    id: 3,
    original_title: "The Movie 3",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
  {
    id: 4,
    original_title: "The Movie 4",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
  {
    id: 5,
    original_title: "The Movie 5",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
  {
    id: 6,
    original_title: "The Movie 6",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
  {
    id: 7,
    original_title: "The Movie 7",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
  {
    id: 8,
    original_title: "The Movie 8",
    poster_path: "https://img.fruugo.com/product/9/75/101193759_max.jpg",
    overview: "whatever you want to say about the movie",
    vote_average: 7.5,
    release_date: "2020-12-15",
    runtime: 98,
  },
];
